In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.array([1,2,3,4,5]) + 3

array([4, 5, 6, 7, 8])

In [ ]:
np.array([[1,2,3],[4,5,6]])*10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
import sympy
x=sympy.symbols('x')
f=x*sympy.exp(x)
print(x)
f_diff=sympy.diff(f)
print(f_diff)

x
x*exp(x) + exp(x)


In [ ]:
# 평균
scores=np.array([42,69,56,41,57,48,65,49,65,58])
np.mean(scores)

55.0

In [ ]:
# 중앙값
np.median(scores)

56.5

In [ ]:
# 최빈값
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [ ]:
# 편차
mean=np.mean(scores)
deviation=scores-mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [ ]:
# 분산
np.var(scores)

86.0

In [ ]:
# 표준편차
np.sqrt(np.var(scores))

9.273618495495704

In [ ]:
np.std(scores)

9.273618495495704

In [ ]:
z=(scores-np.mean(scores))/np.std(scores)
z

array([-1.40182605,  1.50965882,  0.10783277, -1.50965882,  0.21566555,
       -0.75482941,  1.07832773, -0.64699664,  1.07832773,  0.32349832])

In [ ]:
import random
box=[1,2,3,4,5,6,7,8,9,10]
random.sample(box,5)

[1, 3, 8, 2, 5]